apiVersion: v1
kind: Service
metadata:
  name: dev-stedi-redis-final
spec:
  ports:
    - port: 6379
      name: redis
  clusterIP: None
  selector:
    app: dev-stedi-redis-final
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dev-stedi-redis-final
spec:
  selector:
    matchLabels:
      app: dev-stedi-redis-final  # has to match .spec.template.metadata.labels
  serviceName: dev-stedi-redis-final
  replicas: 1
  template:
    metadata:
      labels:
        app: dev-stedi-redis-final  # has to match .spec.selector.matchLabels
    spec:
      containers:
        - name: dev-stedi-redis-final
          image: redis:3.2-alpine
          imagePullPolicy: Always
          args: ["--appendonly", "yes", "--save", "900", "1", "--save", "30", "2"]
          ports:
            - containerPort: 6379
              name: redis
          volumeMounts:
            - name: redis-dev-volume
              mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis-dev-volume
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
