steps:
  # This step builds the container image.
  - name: gcr.io/cloud-builders/docker
    id: Build Stedi API
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/stedi-final:latest
      - ./stedi-private-main
  - name: gcr.io/cloud-builders/docker
    id: Push Stedi API
    args: 
      - push
      - gcr.io/$PROJECT_ID/stedi-final:latest
  - name: gcr.io/cloud-builders/gke-deploy
    id: Deploy Stedi API
    args:
      - run
      - --filename=dev-manifest.yaml
      - --image=gcr.io/$PROJECT_ID/stedi-final:latest
      - --location=us-west1-b
      - --cluster=cluster-2
  - name: gcr.io/cloud-builders/docker
    id: Build Integration Tests
    args:
      - build
      - -t
      - stedi-final-tests
      - ./integration-tests
  - name: gcr.io/cloud-builders/docker
    id: Run Integration Tests
    args:
      - run
      - stedi-final-tests
  - name: gcr.io/cloud-builders/gcloud
    id: Run Production Stedi API Trigger
    args: 
    - pubsub
    - topics
    - publish
    - deploy-prod-stedi-final
    - --message="<3"