apiVersion: apps/v1
kind: Deployment
metadata:
  name: stedi-final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stedi-final
  template:
    metadata:
      labels:
        app: stedi-final
    spec:
      containers:
        - name: stedi-final
          image: gcr.io/power-glove/stedi-final:latest
          ports:
            - containerPort: 4567
          resources:
            limits:
              cpu: ".4"
              memory: "500Mi"
            requests:
              cpu: ".1"
              memory: "250Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 4567
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 4567
            initialDelaySeconds: 3
            periodSeconds: 3
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secrets-dev
                  key: REDIS_PASS
            - name: REDIS_HOST
              value: "dev-stedi-redis-final"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"
            - name: KAFKA_BROKER
              value: "localhost:9092"
            - name: TWILIO_ACCOUNT_SID
              valueFrom:
                secretKeyRef:
                  name: twilio-dev
                  key: TWILIO_ACCOUNT_SID
            - name: TWILIO_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: twilio-dev
                  key: TWILIO_AUTH_TOKEN
            - name: TWILIO_PHONE
              value: "+17146778438"

---

apiVersion: v1
kind: Service
metadata:
  name: stedi-final-loadbalancer
spec:
  selector:
    app: stedi-final
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 4567